### ISSUE TITLE
drop filename not only 'index'

### ISSUE THREAD

**Issue by lokewei** [samit4me/babel-plugin-filenamespace#4]
just like 
`
{
        "root": "app",
        "separator": ".",
        "dropNames": ['action','reducer']
      }
`

**Comment by samit4me** [comment]
@lokewei I agree this would be handy.

Which do you think would be more useful?
1. Drop the listed filenames _(as you suggested)_ **OR**
2. Drop all filenames with a boolean flag **OR**
3. Both of the above

**Comment by lokewei** [comment]
@samit4me yes,all filenames with a boolean flag **OR**

**Comment by samit4me** [comment]
Okay that is great, option 2 it is. Did you want add this option and submit a PR? If not that's cool, I will have a look tonight after work.

**Comment by samit4me** [comment]
@lokewei That feature has been added to v1.1.0, please take a look and let me know if that is what you were after.

**Comment by lokewei** [comment]
Awesome, this is what I want :+1:
